#!/bin/sh


echo "Replacing ~/.wezterm.lua with symlink."
ln -sf "$PWD/wezterm.lua" ~/.wezterm.lua

echo "Installing UbuntuMonoNerd font in ~/.local/share/fonts."
mkdir -p ~/.local/share/fonts
unzip UbuntuMono.zip -d ~/.local/share/fonts/
