#!/usr/bin/env bash

install-neovim() {

  # macos
	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install neovim
		return
	fi

	# windows (git bash)
	if [[ $OSTYPE =~ ^msys ]]; then
		winget install --id neovim.neovim
		return
	fi

	# linux
	mkdir -p ~/.local/bin
	curl -fsSL https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o ~/.local/bin/nvim
	chmod u+x ~/.local/bin/nvim

}

install-neovim
