#!/usr/bin/env bash

install-neovim() {
	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install neovim
		return
	fi
	if [[ $OSTYPE =~ ^msys ]]; then
		winget install --id neovim.neovim
		return
	fi
	sudo add-apt-repository ppa:neovim-ppa/unstable
	sudo apt-get install -y software-properties-common
	sudo apt-get update
	sudo apt-get install -y neovim
}

install-neovim
