#!/usr/bin/env bash

install-weechat() {

	# macos
	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install weechat
		return
	fi

	# windows (git bash)
	if [[ $OSTYPE =~ ^msys ]]; then
		echo "No weechat for Windows. Consider HexChat instead."
		return
	fi

	# linux
	sudo apt-get install -y weechat

}

install-neovim
