#!/usr/bin/env bash

install-wezterm() {

	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install wezterm
		return
	fi

	if [[ $OSTYPE =~ ^msys ]]; then
		winget install --id wez.wezterm
		return
	fi

	# TODO add Linux installer

}

install-wezterm
