#!/usr/bin/env bash

install-wezterm() {

	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install wezterm
		return
	fi

	if [[ $OSTYPE =~ ^msys ]]; then
		winget install --id wez.wezterm
		return
	fi

	mkdir -p ~/.local/bin
	file=20240203-110809-5046fc22-Ubuntu20.04.AppImage
	curl -sSL \
		"https://github.com/wez/wezterm/releases/download/$file" \
		wezterm
	chmod +x ~/.local/bin/wezterm
}

install-wezterm
