#!/usr/bin/env bash


config-wezterm () {
	dir=$(dirname $(dirname "$(realpath "$0")"))/config/wezterm
	target=~/.wezterm.lua

	if [[ $OSTYPE =~ ^msys ]]; then
		: TODO
	elif [[ $(uname -r) =~ microsoft  ]]; then
		: TODO
	fi

	echo "$target/.wezterm.lua -> $dir/wezterm.lua"
	ln -sfn "$dir/wezterm.lua" "$target/.wezterm.lua"
}

config-wezterm
