#!/usr/bin/env bash

config-wezterm() {
	dir="$(dirname "$(dirname "$(realpath "$0")")")/config/wezterm"
	target=~/.wezterm.lua

	if [[ $OSTYPE =~ ^msys ]]; then # MSYS2 or Git-Bash
		: TODO

	elif [[ $(uname -r) =~ microsoft ]]; then # Microsoft WSL2
		: TODO
	fi

	echo "$target/.wezterm.lua -> $dir/wezterm.lua"
	ln -sfn "$dir/wezterm.lua" "$target/.wezterm.lua"
}

config-wezterm
