#!/usr/bin/env bash

install-wezterm() {

	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install wezterm
		return
	fi

	if [[ $OSTYPE =~ ^msys || $(uname -r) =~ microsoft ]]; then
		winget.exe install --id wez.wezterm
		return
	fi

	if type apt-get &>/dev/null; then
		sudo add-apt-repository ppa:wez/wezterm
		sudo apt-get install -y software-properties-common
		sudo apt-get update -y
		sudo apt-get install -y wezterm
		return
	fi

	echo "OS unsupported by this installer: $OSTYPE"

}

install-wezterm
