#!/usr/bin/env bash

install-nodejs() {

	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install nodejs
		return
	fi

	if [[ $OSTYPE =~ ^msys ]]; then
		winget install --id openjs.nodejs
		return
	fi

	if type apt-get &>/dev/null; then
		sudo apt-get install -y nodejs
		return
	fi

	echo "OS unsupported by this installer: $OSTYPE"

}

install-nodejs
