#!/usr/bin/env bash

message="$*"
test -z "$message" && message=save
cd "$DOTFILES" || dot || cd dotfiles || (echo "Unable to cd into dot or dotfiles." >&2 && exit 1)
git add -A .
git commit -m "$message"
if type push;then
	push
else
	git push
fi
