#!/bin/sh

echo "Replacing ~/.bashrc with symlink/copy."
ln -sf "$PWD/bashrc" ~/.bashrc

echo "Replacing ~/.inputrc with symlink/copy."
ln -sf "$PWD/inputrc" ~/.inputrc

echo "Replacing ~/.dircolors with symlink/copy."
ln -sf "$PWD/dircolors" ~/.dircolors
